[package]
name = "hexarr"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", optional = true }

[dev-dependencies]
serde_json = { version = "1" }

[features]
default = []

serde = ["dep:serde"]
